// Bundles the worker and the iframe bootstrap into a string the sandbox embeds in the iframe srcdoc.
import { build } from "esbuild";
import fs from "node:fs";
import { fileURLToPath } from "node:url";

const here = (path) => fileURLToPath(new URL(path, import.meta.url));

async function bundle(entry, define = {}) {
  const result = await build({
    entryPoints: [entry],
    bundle: true,
    format: "iife",
    target: "es2020",
    minify: true,
    write: false,
    define,
  });
  return result.outputFiles[0].text;
}

const worker = await bundle(here("../src/runtime/worker.ts"));
const bootstrap = await bundle(here("../src/host/bootstrap.ts"), {
  __WORKER_SOURCE__: JSON.stringify(worker),
});
fs.writeFileSync(
  here("../src/host/generated.ts"),
  `// Generated by scripts/build-sandbox.mjs. Do not edit.\nexport const BOOTSTRAP_SOURCE = ${JSON.stringify(bootstrap)};\n`,
);
